### PR TITLE
Revert everything back to Feb 20

### PR DESCRIPTION
**Pull request by DGaffney**

### CODE REVIEW

**Review by caiosba — CHANGES_REQUESTED** [review]
Hum... I was verifying the branch this way:

```
git checkout 31732a8ba4e80522012139c74138dfb6fa5ff17d # The "good commit"
git switch -c feb2924-revert-review # New branch from the good commit
git diff feb2924-revert..feb2924-revert-review # Compare branches
```

I wasn't expecting to see any differences, but I did see some.

**Comment by DGaffney** [comment]
> Hum... I was verifying the branch this way:
> 
> ```
> git checkout 31732a8ba4e80522012139c74138dfb6fa5ff17d # The "good commit"
> git switch -c feb2924-revert-review # New branch from the good commit
> git diff feb2924-revert..feb2924-revert-review # Compare branches
> ```
> 
> I wasn't expecting to see any differences, but I did see some.

Looks like other than the ci file its all just newlines or lackthereof - adding ci file now and should be good

**Review by caiosba — APPROVED** [review]
Verified this way:

```
git checkout 31732a8ba4e80522012139c74138dfb6fa5ff17d # The "good commit"
git switch -c feb2924-revert-review # New branch from the good commit
git diff --ignore-all-space feb2924-revert..feb2924-revert-review # Compare branches
```

No differences.

**Comment by skyemeedan** [comment]
I don't have context for this PR,  is it prep in case we need an emergency rollback during deployment?

**Comment by caiosba** [comment]
> I don't have context for this PR, is it prep in case we need an emergency rollback during deployment?

We've decided to not proceed with the video refactoring deployment this Sunday, so the idea of this PR is to revert the work in `master` and then move it to a branch, like Alegre, API and Web.

**Pull request merged**
